# Generated by Django 3.0.6 on 2020-05-26 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('realName', models.CharField(max_length=50)),
                ('timeZone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='eventTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventTime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventDetail')),
            ],
        ),
    ]
