# Generated by Django 3.0.6 on 2020-05-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200526_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
