# Generated by Django 3.0.6 on 2020-05-27 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200527_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtime',
            name='eventDetail',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.eventDetail'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='realName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='timeZone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='events',
        ),
    ]
